### PR TITLE
Ensure Polymer 3 Modulizer compatibility

### LINKED ISSUE #23: Ensure Polymer 3 Modulizer compatibility
See “Generic steps” at vaadin/components-team-tasks#326

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #23 

This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-demo-helpers/26)

### CODE REVIEW

**Comment by limonte** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/advanced-demos.html, line 29 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-demo-helpers/26#-L87OzwlNEIGtyqvDlD9:-L87OzwlNEIGtyqvDlDA:b-ix3n7q) ([raw file](https://github.com/vaadin/vaadin-demo-helpers/blob/ef6853f100e329116814d0127400163a90326dae/demo/advanced-demos.html#L29)):*
> ```HTML
>     customElements.define(AdvancedDemos.is, AdvancedDemos);
>   </script>
> </dom-module>
> ```

nit: use VSCode settings`"files.insertFinalNewline": true` to prevent Reviewable and GitHub from showing those ugly red characters :)

https://eslint.org/docs/rules/eol-last

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-demo-helpers/26#-:-L87OuMCF6ZdytTWg24t:bnfp4nl)*

**Comment by web-padawan** [comment]
Currently the modulizer does not do anything with the `Polymer.importHref` so it appears to work in Chrome, under native HTML imports implementation. We will have to revise it in the future, though. 

Not a blocker to me, if we don't expect demos to work in all browsers. Probably we will have to use `import()` later.

---

Reviewed 1 of 9 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-demo-helpers/26#-:-L8HwPKA2k1EmcQPxYCe:b-ogyweq)*

**Comment by web-padawan** [comment]
Refactored to use script tags for P3 compatibility and added the tests.

---

Review status: 5 of 17 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-demo-helpers/26#-:-L8aKp-BpJA-c_89Ws59:b-i9uayj)*

**Comment by platosha** [comment]
Reviewed 3 of 9 files at r1, 2 of 3 files at r2, 12 of 12 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[package.json, line 25 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-demo-helpers/26#-L8aaC2TeW6QeZ8Z_tKk:-L8aaC2TeW6QeZ8Z_tKl:b-dug497) ([raw file](https://github.com/vaadin/vaadin-demo-helpers/blob/73a5bbed57c60cb43a5cbcd4c58722facc04519f/package.json#L25)):*
> ```JSON
>     "gulp-modify": "latest",
>     "gulp-concat": "latest",
>     "polymer-cli": "^1.2.0"
> ```

Maybe remove `polymer-cli` from the devDeps, as advised in the “General steps”?

---

*[demo/all-imports.html, line 2 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-demo-helpers/26#-L8ab4OPrgb2SNn-ToEO:-L8ab4OPrgb2SNn-ToEP:bya2kdq) ([raw file](https://github.com/vaadin/vaadin-demo-helpers/blob/73a5bbed57c60cb43a5cbcd4c58722facc04519f/demo/all-imports.html#L2)):*
> ```HTML
> <link rel="import" href="basic-demos.html">
> <link rel="import" href="advanced-demos.html">
> ```

Having to make this in every element would be annoying.

Let me enable conversion for demos on the magi side instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-demo-helpers/26)*

**Comment by web-padawan** [comment]
Review status: 10 of 19 files reviewed at latest revision, 2 unresolved discussions.

---

*[package.json, line 25 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-demo-helpers/26#-L8aaC2TeW6QeZ8Z_tKk:-L8at9GqZdQ15XO5Szoz:btpsul1) ([raw file](https://github.com/vaadin/vaadin-demo-helpers/blob/73a5bbed57c60cb43a5cbcd4c58722facc04519f/package.json#L25)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Maybe remove `polymer-cli` from the devDeps, as advised in the “General steps”?
</blockquote></details>

The whole `"devDependencies"` section is not needed here, actually. Done.

---

*[demo/advanced-demos.html, line 29 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-demo-helpers/26#-L87OzwlNEIGtyqvDlD9:-L8atoBbF9AXi9RQh0Uy:b-896fix) ([raw file](https://github.com/vaadin/vaadin-demo-helpers/blob/ef6853f100e329116814d0127400163a90326dae/demo/advanced-demos.html#L29)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

nit: use VSCode settings`"files.insertFinalNewline": true` to prevent Reviewable and GitHub from showing those ugly red characters :)

https://eslint.org/docs/rules/eol-last
</blockquote></details>

Done.

---

*[demo/all-imports.html, line 2 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-demo-helpers/26#-L8ab4OPrgb2SNn-ToEO:-L8au-KI9iHya9LSxYVZ:bss4a2b) ([raw file](https://github.com/vaadin/vaadin-demo-helpers/blob/73a5bbed57c60cb43a5cbcd4c58722facc04519f/demo/all-imports.html#L2)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Having to make this in every element would be annoying.

Let me enable conversion for demos on the magi side instead.
</blockquote></details>

Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-demo-helpers/26)*

**Comment by web-padawan** [comment]
Waiting for the new `magi-cli` in order to verify that demo conversion works, and then should be ready to go.

---

Review status: 10 of 19 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-demo-helpers/26#-:-L8au63B0zWtQVQkoW4O:br6ix9w)*

**Comment by web-padawan** [comment]
Reviewed 1 of 3 files at r2, 8 of 12 files at r4.
Review status: 17 of 19 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-demo-helpers/26)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 1 of 9 files at r1, 1 of 12 files at r3, 5 of 12 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-demo-helpers/26#-:-L8b8u-YlrdcSbHQ6cWq:bnfp4nl)*

**Pull request merged**
