### PR TITLE
Run callbacks for new demo instances

### LINKED ISSUE #12: Components lose data after navigation
This was reported in https://github.com/vaadin/vaadin-combo-box/issues/584

### Description
In `basic examples` demo,  all comboboxes lose data after coming back from e.g. `object items` view.

### Expected outcome
When coming back, the comboboxes should have same values (at least initial).

### Actual outcome
the comboboxes are empty, and all items are empty.

### Steps to reproduce
1. Run `polymer serve --open`, on `vaadin-combo-box` project, the browser opens
2. Add `demo`, e.g. http://127.0.0.1:8080/components/vaadin-combo-box/demo
3. You will see in "Configuring the Combo Box" comoboxes, "Element" has all elements values, and "Read Only" value is "Carbon".
4. Click "Object Items" to navigate away
5. Click "Basic Examples" to return back.
6. You expect the "Element" to have all values, "Read Only" to have "Carbon", but they are all empty, same thing applies to all comboboxes in the view.

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #12 
Fixes vaadin/vaadin-combo-box#584

Since the demo frame creates new instances of individual demo pages on navigation, the callback should be run for every new instance or the demo doesn't work properly.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-demo-helpers/16)

### CODE REVIEW

**Comment by web-padawan** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-demo-helpers/16#-:-L0xMn0_KmopUCnrtc0x:bnfp4nl)*

**Comment by vicsstar** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-demo-helpers/16#-:-L0xS8vwIbrVa3z78MRF:bnfp4nl)*

**Comment by vicsstar** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-demo-helpers/16)*

**Comment by YuriyVaadin** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-demo-helpers/16#-:-L0y3CzZsGL14iOdXZa8:bnfp4nl)*

**Pull request merged**
